### PR TITLE
Improve numerical stability

### PR DESCRIPTION
**Pull request by odow**
I finally tracked down a long standing numerical issue in SDDP.jl (ref https://github.com/odow/SDDP.jl/issues/6#issuecomment-343022931).

A state variable can be slightly infeasible in the optimal solution of one subproblem and satisfy the feasibility tolerances. However when set as the incoming state variable in the next subproblem, it can cause the full problem to be infeasible. 

The fix is to project the variable value back into the proper bounds. 

cc @leclere @blegat @frapac @joaquimg you probably want to implement this?

### CODE REVIEW

**Comment by blegat** [comment]
Thanks for the warning, that's indeed a good idea. Which solver returns a slightly infeasible solution ? Projecting to bounds will fix bound infeasibility but do you also observe constraint infeasibility ?

**Comment by odow** [comment]
Gurobi. 

> Projecting to bounds will fix bound infeasibility but do you also observe constraint infeasibility ?

We typically assume relatively complete recourse so no. In your situation with feasibility cuts, I guess there is the potential. That would be much harder to fix.

**Comment by joaquimg** [comment]
You were using barrier method or simplex? or default?

**Comment by odow** [comment]
All defaults.

**Pull request merged**
