### PR TITLE
Allow Historical to sample sequentially

### LINKED ISSUE #414: Historical ForwardPass sampling scheme
Write a forward pass sampling scheme that samples from historical data with some probability.

### PR DESCRIPTION
**Pull request by odow**
Closes #414 

I didn't run the tests locally. Let's see what breaks...

### CODE REVIEW

**Comment by adow031** [comment]
I've tried to force compatibility with SDDP 0.3.16 for my CI tests.
But I get this error:
```
 SDDP [f4570300] log:
 ├─possible versions are: [0.1.0, 0.2.0-0.2.4, 0.3.0-0.3.15] or uninstalled
 └─restricted to versions 0.3.16-0.3 by an explicit requirement — no versions left
```
It is just a matter of waiting for the new version to appear in the repo that Github actions is pulling from?

Tony.

**Comment by odow** [comment]
It's not released yet.

**Comment by odow** [comment]
I wanted to fix this documentation failure first: https://github.com/odow/SDDP.jl/runs/2843898147

**Comment by adow031** [comment]
Oh ok. It's good that it's not on my end. I probably should try to understand the concept of a release at some point.

**Comment by odow** [comment]
The new version should be available once https://github.com/JuliaRegistries/General/pull/39005 is merged.

**Pull request merged**
