### PR TITLE
Fix custom_recorders example

### PR DESCRIPTION
**Pull request by Thuener**

### CODE REVIEW

**Comment by odow** [comment]
Thanks! We should probably make these doctests to avoid these errors.

**Comment by odow** [comment]
So the doc failure on Travis isn't your fault. But I'm not sure of the cause. Might be a documenter issue?

**Comment by Thuener** [comment]
Maybe is the "open = true"?

**Comment by odow** [comment]
I can't reproduce this locally. https://github.com/odow/SDDP.jl/pull/244 is incoming with a fix, but it might conflict with this, so I'll merge now and deal with the consequences in #244.

**Pull request merged**
