### PR TITLE
Discount prices over time by interest rate

### PR DESCRIPTION
**Pull request by bfpc**
It is usual, in long-term planning, to apply a (usually fixed) interest rate to the future cost.

I expect this small change does everything it's supposed to, but I'm not 100% sure.  I was wondering if this should create an entirely new discountedValueFunction.jl, but I don't see the point.  Maybe, for changing interest rates over time this could be justified...

I have tested against examples/simple_objective_noise.jl , examples/Newsvendor/newsvendor.jl and examples/HydroValleys/hydro_valley_tests.jl

### CODE REVIEW

**Comment by odow** [comment]
I've implemented discounting in the past by multiplying the stage objective by the discount factor:
```julia
SDDPModel() do sp, t
    ρ = 0.95
    @stageobjective(sp, ρ^(t-1) * ( ... normal objective ... ) )
end
```
Does this achieve the same thing?

**Comment by odow** [comment]
As an aside, you can run the packages unit tests by opening a new Julia REPL and running `Pkg.test("SDDP")`. This will run all the tests in the [`/test`](https://github.com/odow/SDDP.jl/tree/master/test) folder. If you run the tests (or look at the Travis log), you'll see that [this test](https://github.com/odow/SDDP.jl/blob/master/test/stageobjectives.jl#L17) is now failing because JuMP must reorder the variables now that the coefficients have changed.

It would be good to add a new example showing how to introduce a discount rate and confirm that it converges to the discounted lower bound.

**Comment by bfpc** [comment]
The explicit exponential term should indeed yield the same result - it's just that it seems more natural to discount at every stage.

Should I correct the failing test, or is it better to encourage incorporating the discount at each `@stageobjective`?

**Comment by odow** [comment]
The general rule I have followed is, where possible, to avoid incorporating special features than can be implemented by the user (for example, AR(N) processes for rainfall). 

I have a much better way to implement this that naturally extends to infinite horizon models with discount factors, however I'm not planning on implementing it until after I submit my PhD (~May). Unfortunately it is linked to #92 and will require a significant re-write of the library.

In the meantime, I would gladly accept a PR for a new example with discounting that solves a couple of times for different discount factors showing the different results.

**Comment by odow** [comment]
Closing in favour of #138. This just needs some documentation until we can redo this better.

**Pull request closed without merging**
